config/routes.rb
Rails.application.routes.draw do
  get 'accounts/search'
  resources :account_entries
  resources :accounts do
    member do
      post 'recalc'
    end
  end
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #if logged in, root is home page
  authenticated :user do
    root to: 'home#user_index'
  end
  authenticated :admin do
    root to: 'home#admin_index'
  end
  #otherwise root is login page
  root to: redirect('/users/sign_in')

  devise_for :users
  get 'home/index'
  get 'home/user_index'
  get 'home/admin_index'
  get 'home/help'
  get 'home/contact'

  get '/restricted', to: 'home#restricted', as: :restricted

  get 'products/search'

  resources :settings, :except => [:new, :create, :destroy, :show]
  get 'products/quota_dashboard'
  resources :products  do
    member do
      get 'view_transactions_for' => 'products#transactions'
      get 'view_inventory_for' => 'products#inventory'
    end
  end
  resources :users
  resources :stocks  do
    member do
      get 'recalc' => 'stocks#recalc'
#      get 'view_stats_for' => 'stocks#stats'   #unused
    end
  end


end

app/models/account_entry.rb
class AccountEntry < ApplicationRecord
  belongs_to :account
end

app/controllers/account_entries_controller.rb
class AccountEntriesController < ApplicationController
  before_action :set_account_entry, only: [:show, :edit, :update, :destroy]

  # GET /account_entries
  # GET /account_entries.json
  def index
    @account_entries = AccountEntry.all
  end

  # GET /account_entries/1
  # GET /account_entries/1.json
  def show
  end

  # GET /account_entries/new
  def new
    @account_entry = AccountEntry.new
  end

  # GET /account_entries/1/edit
  def edit
  end

  # POST /account_entries
  # POST /account_entries.json
  def create
    @account_entry = AccountEntry.new(account_entry_params)

    respond_to do |format|
      if @account_entry.save
        @account_entry.account.recalc
        format.html { redirect_to @account_entry.account, notice: 'Account entry was successfully created.' }
        format.json { render :show, status: :created, location: @account_entry }
      else
        format.html { render :new }
        format.json { render json: @account_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_entries/1
  # PATCH/PUT /account_entries/1.json
  def update
    respond_to do |format|
      if @account_entry.update(account_entry_params)
        @account_entry.account.recalc
        format.html { redirect_to @account_entry.account, notice: 'Account entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @account_entry }
      else
        format.html { render :edit }
        format.json { render json: @account_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_entries/1
  # DELETE /account_entries/1.json
  def destroy
    @account_entry.destroy
    @account_entry.account.recalc
    respond_to do |format|
      format.html { redirect_to @account_entry.account, notice: 'Account entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_entry
      @account_entry = AccountEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_entry_params
      params[:account_entry][:amount]=params[:account_entry][:amount].sub(",","")
      params.require(:account_entry).permit(:account_id, :date, :amount, :balance, :description)
    end
end

app/helpers/account_entries_helper.rb
module AccountEntriesHelper
end

app/views/account_entries/_form.html.erb
<%= form_for(account_entry) do |f| %>
  <% if account_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_entry.errors.count, "error") %> prohibited this account_entry from being saved:</h2>

      <ul>
      <% account_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account_id %>:
    <%= f.hidden_field :account_id %>
    <%= @account_entry.account.name%>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date, "class" => 'datepicker' %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <%= f.hidden_field :balance %>
  
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
$(function() {
  $('.datepicker').datepicker({
      dateFormat: 'yy-mm-dd',
      showButtonPanel: true,  //show today and done buttons - done button is actually close or cancel
      closeText : "Cancel",
      changeMonth: true,
      changeYear: true,
      yearRange: "c-100:c+100"    //c=currently selected year; you can also hard code it: "2005:2015" 
      //showOtherMonths: true,  //show days in the months before and after
      //selectOtherMonths: true //allow selecting days in the months before and after
  });
});
</script>

app/views/account_entries/edit.html.erb
<h1>Editing Account Entry</h1>

<%= render 'form', account_entry: @account_entry %>

<%= link_to 'Show', @account_entry %> |
<%= link_to 'Back', account_entries_path %>

app/views/account_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Account Entries</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Balance</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_entries.each do |account_entry| %>
      <tr>
        <td><%= account_entry.account %></td>
        <td><%= account_entry.date %></td>
        <td><%= account_entry.amount %></td>
        <td><%= account_entry.balance %></td>
        <td><%= account_entry.description %></td>
        <td><%= link_to 'Show', account_entry %></td>
        <td><%= link_to 'Edit', edit_account_entry_path(account_entry) %></td>
        <td><%= link_to 'Destroy', account_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account Entry', new_account_entry_path %>

app/views/account_entries/new.html.erb
<h1>New Account Entry</h1>

<%= render 'form', account_entry: @account_entry %>

<%= link_to 'Back', account_entries_path %>

app/views/account_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @account_entry.account %>
</p>

<p>
  <strong>Date:</strong>
  <%= @account_entry.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @account_entry.amount %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account_entry.balance %>
</p>

<p>
  <strong>Description:</strong>
  <%= @account_entry.description %>
</p>

<%= link_to 'Edit', edit_account_entry_path(@account_entry) %> |
<%= link_to 'Back', account_entries_path %>