config/routes.rb
Rails.application.routes.draw do
  get 'accounts/search'
  resources :account_entries
  resources :accounts do
    member do
      post 'recalc'
    end
  end
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #if logged in, root is home page
  authenticated :user do
    root to: 'home#user_index'
  end
  authenticated :admin do
    root to: 'home#admin_index'
  end
  #otherwise root is login page
  root to: redirect('/users/sign_in')

  devise_for :users
  get 'home/index'
  get 'home/user_index'
  get 'home/admin_index'
  get 'home/help'
  get 'home/contact'

  get '/restricted', to: 'home#restricted', as: :restricted

  get 'products/search'

  resources :settings, :except => [:new, :create, :destroy, :show]
  get 'products/quota_dashboard'
  resources :products  do
    member do
      get 'view_transactions_for' => 'products#transactions'
      get 'view_inventory_for' => 'products#inventory'
    end
  end
  resources :users
  resources :stocks  do
    member do
      get 'recalc' => 'stocks#recalc'
#      get 'view_stats_for' => 'stocks#stats'   #unused
    end
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accountant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
    table {
      border-collapse: separate;
      border-spacing: 10px 0;
    }
    td {
      padding: 5px 0;
    }
  </style>
</head>
<body>




<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Accountant', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <% if user_signed_in? or admin_signed_in? %>
          <li><%#= link_to 'Restricted', restricted_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
          <li><%= link_to 'Accounts', accounts_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Welcome <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              <!--
              <%# if(current_user.admin?) %>
                <li><%#= link_to 'Users', users_path %></li>
                <li><%#= link_to 'Settings', settings_path %></li>
              <%# end %>
              -->
            </ul>
          </li>
        <% elsif admin_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Welcome <%= current_admin.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_admin_registration_path %></li>
              <li><%= link_to 'Log out', destroy_admin_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In / Sign Up', new_user_session_path %></li>
          <!--li><%#= link_to '', new_user_registration_path %></li-->
          <li><%= link_to "Admin", new_admin_session_path if Rails.env=="development" %></li>
        <% end %>
      </ul>

      <% if user_signed_in? or admin_signed_in? %>
      <br>
          <!---search--->
          <input id=searchstring>
          <input type=button value="Account" class=searchbutton path=accounts>
          <!---end search--->
      <% end %>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
    <div id="searchresult"></div>

    <h1><%= yield :header %></h1>
  <%= yield %>
</div>

</body>
</html>
<script>
  //search
  //this is an all purpose search function for several search buttons
  //path is specified in the search button
  //and is in plural form
  $(".searchbutton").click(function(event){
    var searchstring=$('#searchstring').val();
    //if(searchstring.trim().length==0)return;
    var url="<%=request.protocol+request.host+':'+request.port.to_s%>";
    url=url+"/"+$(this).attr("path")+"/search"
    url=url+"?searchstring="+searchstring;
    url=url+"&path="+$("#path").val();
    $.ajax({
      url: url, 
      success: function(result){
 		    $("#searchresult").html(result);
      }})
  });
</script>