config/routes.rb
Rails.application.routes.draw do
  get 'accounts/search'
  resources :account_entries
  resources :accounts do
    member do
      post 'recalc'
    end
  end
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #if logged in, root is home page
  authenticated :user do
    root to: 'home#user_index'
  end
  authenticated :admin do
    root to: 'home#admin_index'
  end
  #otherwise root is login page
  root to: redirect('/users/sign_in')

  devise_for :users
  get 'home/index'
  get 'home/user_index'
  get 'home/admin_index'
  get 'home/help'
  get 'home/contact'

  get '/restricted', to: 'home#restricted', as: :restricted

  get 'products/search'

  resources :settings, :except => [:new, :create, :destroy, :show]
  get 'products/quota_dashboard'
  resources :products  do
    member do
      get 'view_transactions_for' => 'products#transactions'
      get 'view_inventory_for' => 'products#inventory'
    end
  end
  resources :users
  resources :stocks  do
    member do
      get 'recalc' => 'stocks#recalc'
#      get 'view_stats_for' => 'stocks#stats'   #unused
    end
  end


end

app/models/account.rb
class Account < ApplicationRecord
  has_many :account_entries

  def recalc
    balance=0
    
    self.account_entries.order('date,id').each do |e|
      balance+=e.amount
      e.update(balance:balance)
    end
    
    self.update(balance:balance)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :recalc]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account_entries=@account.account_entries.order('date desc,id desc').paginate(page: params[:page], per_page: Constants::RECORDS_PER_PAGE)
    @account_entry=AccountEntry.new
    @account_entry.account=@account
    @account_entry.date=Date.today
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @searchstring=params['searchstring']
    
=begin
    #if searchstring is empty, do nothing
    if(@searchstring.empty?)
      @accounts=[]
      return
    end
=end
    
    @keywords=params['searchstring'].split(" ")

    #put together query as string
    query=""
    @keywords.each do |k|
      #add 'or' if query string is not empty
      if(!query.empty?) then query+=" or " end
      query+="name like '%#{k}%'"
      query+=" or description like '%#{k}%'"
    end  
    @accounts=Account.where(query).order(:name).paginate(page: params[:page], per_page: Constants::RECORDS_PER_PAGE)

    respond_to do |format|
        format.html { render :layout => !request.xhr? }
        # other formats
    end
  end

  def recalc
    @account.recalc
    redirect_to @account
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :description, :balance)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account_entries.html.erb
<%= will_paginate @account_entries, :params => {:controller => 'accounts', :action => 'show'}, class:"pagination account_participating_entries_pagination" %>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>In</th>
      <th>Out</th>
      <th>Balance</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_entries.each do |account_entry| %>
      <tr>
        <td><%= account_entry.date.to_formatted_s(:pretty) %></td>
        <td><%= number_with_delimiter(account_entry.amount, :delimiter => ',') if account_entry.amount>=0%></td>
        <td><%= number_with_delimiter(account_entry.amount, :delimiter => ',') if account_entry.amount<0%></td>
        <td><%= account_entry.balance %></td>
        <td><%= account_entry.description %></td>
        <td><%= link_to 'Edit', edit_account_entry_path(account_entry) %></td>
        <td><%= link_to 'Destroy', account_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @account_entries, :params => {:controller => 'accounts', :action => 'show'}, class:"pagination account_participating_entries_pagination" %>

<script>
$("div.account_participating_entries_pagination").find("a").click(function (e) 
{
  e.preventDefault();
  $.ajax({
    url: $(this).attr("href").replace('?', '/participating_entries?'), 
    success: function(result){
	    $("#entries").html(result);
    }})

});
</script>

app/views/accounts/_form.html.erb
<%= form_for(account) do |f| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.description %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/search.html.erb
<h1>Account Search</h1>

<table>
<tr>
	<td>Name</td>
	<td>Description</td>
</tr>
<% @accounts.each do |p|%>
  <tr valign=top>
	  <td><%=link_to(p.name, account_path(p)) %></td>
	  <td><%=p.description %></td>
	  <td><%=link_to("Edit", edit_account_path(p)) %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @accounts, :params => {:controller => 'accounts', :action => 'search'} %>

<hr>



app/views/accounts/show.html.erb
<!--
<p id="notice"><%= notice %></p>
-->

<h2>Account: <%= @account.name %></h2>

<%= @account.description %>

<p>
  <strong>Balance:</strong>
  <%= number_with_delimiter(@account.balance, :delimiter => ',') %>
</p>
<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %> |
<%= link_to 'Recalculate', recalc_account_path, method:"post" %> |

<hr>
<h3>New Account Entry</h3>

<% account_entry=@account_entry%>
<%= form_for(account_entry) do |f| %>
  <% if account_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_entry.errors.count, "error") %> prohibited this account_entry from being saved:</h2>

      <ul>
      <% account_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :account_id %>
  <table>
    <tr>
      <td><%= f.label :date %></td>
      <td><%= f.label :amount %></td>
      <td><%= f.label :description %></td>
      <td></td>
    </tr>
    <tr>
      <td><%= f.text_field :date, "class" => 'datepicker' %> </td>
      <td><%= f.text_field :amount %></td>
      <td><%= f.text_field :description %></td>
      <td><%= f.submit %></td>
    </tr>
  </table>
<% end %>

<hr>
<h3>Account Entries</h3>
<div id=products>
<%= render 'account_entries' %>
</div>

<script>
$(function() {
  $('.datepicker').datepicker({
      dateFormat: 'yy-mm-dd',
      showButtonPanel: true,  //show today and done buttons - done button is actually close or cancel
      closeText : "Cancel",
      changeMonth: true,
      changeYear: true,
      yearRange: "c-100:c+100"    //c=currently selected year; you can also hard code it: "2005:2015" 
      //showOtherMonths: true,  //show days in the months before and after
      //selectOtherMonths: true //allow selecting days in the months before and after
  });
});
</script>